// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  "use strict";
  var $, Backbone, PubSub, app, _;
  _ = require("underscore");
  $ = require("jquery");
  Backbone = require("backbone");
  PubSub = require("pubsub");
  app = module.exports;
  app.root = "/photosite/";
  return console.log(app);
});
