// Generated by CoffeeScript 1.6.3
require.config({
  paths: {
    "vendor": "vendor",
    "lib": "lib",
    "underscore": "vendor/bower_components/lodash/dist/lodash.underscore",
    "jquery": "vendor/bower_components/jquery/jquery",
    "backbone": "vendor/bower_components/backbone/backbone",
    "pubsub": "lib/pubsub"
  },
  shim: {
    "backbone": {
      deps: ["jquery", "underscore"],
      exports: "Backbone"
    }
  }
});
