// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  "use strict";
  var $, Backbone, PubSub, app;
  $ = require("jquery");
  Backbone = require("backbone");
  app = require("app");
  PubSub = require("pubsub");
  return Backbone.View.extend({
    el: '#loader',
    initialize: function() {
      this.$el = $(this.el);
      this.$progress = this.$el.children();
      this.pubSub = {
        'app:rendered': this.onAfterRender
      };
      return PubSub.attach(this.pubSub, this);
    },
    onAfterRender: function() {
      var $els, imageCount, l, total, _results;
      this.$progress.html('0');
      this.$el.show();
      $els = app.$body.find('img');
      total = $els.length;
      imageCount = 0;
      l = total;
      if (l > 0) {
        _results = [];
        while (l--) {
          _results.push($($els[l]).load(_.bind(function(e) {
            ++imageCount;
            $(e.currentTarget).addClass("loaded");
            this.$progress.html(((imageCount / total) * 100) | 0);
            if (total === imageCount) {
              return this.done();
            }
          }, this)));
        }
        return _results;
      } else {
        return this.done();
      }
    },
    done: function() {
      PubSub.trigger('app:preloaded');
      return this.$el.fadeOut();
    }
  });
});
