// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  "use strict";
  var $, Backbone, PubSub, app;
  $ = require("jquery");
  Backbone = require("backbone");
  app = require("app");
  PubSub = require("pubsub");
  return Backbone.View.extend({
    el: '#loader',
    initialize: function() {
      this.$el = $(this.el);
      this.$progress = this.$el.children();
      this.pubSub = {
        'app:rendered': this.onAfterRender
      };
      return PubSub.attach(this.pubSub, this);
    },
    onAfterRender: function() {
      var $els, imageCount, l, total, _results;
      this.$progress.html('0');
      this.$el.show();
      console.log(app.view);
      $els = app.$body.find('img');
      total = $els.length;
      imageCount = 0;
      l = total;
      if (l > 0) {
        _results = [];
        while (l--) {
          $($els[l]).on('load', function() {});
          ++imageCount;
          this.$progress.html((total / imageCount) * 100);
          if (total === imageCount) {
            _results.push(this.done());
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      } else {
        return this.done();
      }
    },
    done: function() {
      return this.$el.hide();
    }
  });
});
