// Generated by CoffeeScript 1.6.3
(function() {
  require(["config"], function() {
    return require(["app", "router", "loader", "appView"], function(app, Router, Loader, appView) {
      app.loader = new Loader();
      app.view = new appView();
      app.router = new Router();
      Backbone.history.start({
        pushState: true,
        silent: true,
        root: app.root
      });
      return $(document).ready(function() {
        return app.init();
      });
    });
  });

}).call(this);
