// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  "use strict";
  var Backbone;
  Backbone = require("backbone");
  return module.exports = Backbone.Router.extend({
    routes: {
      "*": "someRoute"
    },
    someRoute: function() {
      return console.log("Welcome to your / route.");
    }
  });
});
