// Generated by CoffeeScript 1.6.3
define(["app", "pubsub"], function(app, PubSub) {
  "use strict";
  return Backbone.Router.extend({
    routes: {
      '*path': 'someRoute'
    },
    someRoute: function(path) {
      var ajaxPromise;
      ajaxPromise = $.Deferred(function(deferred) {
        var href;
        href = app.baseUrl + path;
        return $.ajax(href, {
          type: 'GET',
          dataType: 'html',
          error: function(jqXHR, textStatus, errorThrown) {
            console.log("AJAX Error: " + textStatus);
            return deferred.fail(textStatus);
          },
          success: function(data, textStatus, jqXHR) {
            return deferred.resolve(data);
          }
        });
      }).promise();
      ajaxPromise.done(function(html) {
        return PubSub.trigger('app:loaded', html);
      });
      return ajaxPromise.fail(function(error) {
        return console.log(error);
      });
    }
  });
});
