// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  "use strict";
  var $, Backbone, PubSub, _;
  _ = require("underscore");
  $ = require("jquery");
  Backbone = require("backbone");
  PubSub = require("pubsub");
  return module.exports = Backbone.View.extend({});
});
